const products = [
    {
        id: 1,
        country: 'Франция',
        author: 'Марсель Руссо',
        title: 'Охота Амура',
        features: 'Холст, масло (50х80)',
        price: '14 500',
        image: 'img/products/france/amurs-hunt.webp',
    },
    {
        id: 2,
        country: 'Франция',
        author: 'Анри Селин',
        title: 'Дама с собачкой',
        features: 'Акрил, бумага (50х80)',
        price: '16 500',
        image: 'img/products/france/lady-with-the-dog.webp',
    },
    {
        id: 3,
        country: 'Франция',
        author: 'Франсуа Дюпон',
        title: 'Процедура',
        features: 'Цветная литография (40х60)',
        price: '20 000',
        image: 'img/products/france/procedure.webp',
    },
    {
        id: 4,
        country: 'Франция',
        author: 'Луи Детуш',
        title: 'Роза',
        features: 'Бумага, акрил (50х80)',
        price: '12 000',
        image: 'img/products/france/rose.webp',
    },
    {
        id: 5,
        country: 'Франция',
        author: 'Франсуа Дюпон',
        title: 'Птичья трапеза',
        features: 'Цветная литография (40х60)',
        price: '22 500',
        image: 'img/products/france/birds-meal.webp',
    },
    {
        id: 6,
        country: 'Франция',
        author: 'Пьер Моранж',
        title: 'Пейзаж с рыбой',
        features: 'Цветная литография (40х60)',
        price: '20 000',
        image: 'img/products/france/landscape-with-fish.webp',
    },
    {
        id: 7,
        country: 'Германия',
        author: 'Курт Вернер',
        title: 'Над городом',
        features: 'Цветная литография (40х60)',
        price: '16 000',
        image: 'img/products/germany/above-the-city.webp',
    },
    {
        id: 8,
        country: 'Германия',
        author: 'Макс Рихтер',
        title: 'Птенцы',
        features: 'Холст, масло (50х80)',
        price: '14 500',
        image: 'img/products/germany/younglings.webp',
    },
    {
        id: 9,
        country: 'Германия',
        author: 'Мартин Майер',
        title: 'Среди листьев',
        features: 'Цветная литография (40х60) ',
        price: '20 000',
        image: 'img/products/germany/among-the-leaves.webp',
    },
    {
        id: 10,
        country: 'Германия',
        author: 'Герман Беккер',
        title: 'Яркая птица',
        features: 'Цветная литография (40х60)',
        price: '13 000',
        image: 'img/products/germany/bright-bird.webp',
    },
    {
        id: 11,
        country: 'Германия',
        author: 'Вульф Бауэр',
        title: 'Дятлы',
        features: 'Бумага, акрил (50х80)',
        price: '20 000',
        image: 'img/products/germany/woodpeckers.webp',
    },
    {
        id: 12,
        country: 'Германия',
        author: 'Вальтер Хартманн',
        title: 'Большие воды',
        features: 'Бумага, акрил (50х80)',
        price: '23 000',
        image: 'img/products/germany/big-waters.webp',
    },
    {
        id: 13,
        country: 'Англия',
        author: 'Пол Смит',
        title: 'Дикий зверь',
        features: 'Акварель, бумага (50х80)',
        price: '19 500',
        image: 'img/products/england/wild-animal.webp',
    },
    {
        id: 14,
        country: 'Англия',
        author: 'Джон Уайт',
        title: 'Скалистый берег',
        features: 'Цветная литография (40х60)',
        price: '17 500',
        image: 'img/products/england/rocky-shore.webp',
    },
    {
        id: 15,
        country: 'Англия',
        author: 'Джим Уотсон',
        title: 'Река и горы',
        features: 'Акварель, бумага (50х80)',
        price: '20 500 руб',
        image: 'img/products/england/river-and-mountains.webp',
    },
    {
        id: 16,
        country: 'Англия',
        author: 'Юджин Зиллион',
        title: 'Белый попугай',
        features: 'Цветная литография (40х60)',
        price: '15 500',
        image: 'img/products/england/white-parrot.webp',
    },
    {
        id: 17,
        country: 'Англия',
        author: 'Эрик Гиллман',
        title: 'Ночная рыба',
        features: 'Бумага, акрил (50х80)',
        price: '12 500',
        image: 'img/products/england/night-fish.webp',
    },
    {
        id: 18,
        country: 'Англия',
        author: 'Альфред Барр',
        title: 'Рыжий кот',
        features: 'Цветная литография (40х60)',
        price: '21 000',
        image: 'img/products/england/ginger-cat.webp',
    }
];